### ISSUE TITLE
Suggestion:Implement a FAR like voxel modeling system for stealth

### ISSUE THREAD

**Issue by EventHorizon27** [PapaJoesSoup/BDArmory#43] opened 2016-09-04 03:41 UTC
Ferram4 supposedly offered at one point to help implement a voxel system for radar stealth( and it would be nice to have the same kind of system for thermal stealth), and now may be the time to do so. With more parts getting added, and the heating system integrated fully with surface and interior temperatures, it would now be possible to properly integrate a system that would allow for the building of stealth aircraft, and would be possible to disable.

**Comment by TheDestroyer111** [comment] 2016-09-04 07:18
If it would be possible to disable, or as a separate mod, then yes, but if not possible to disable, then never ever. Such things take a huge performance impact. Also, this might have some compatibility problems. For example, while IRL propellers have a very high RCS (radar cross section), and it *may* work for stock-based props, it may be glitchy in an unfixable way for modded props (like in Firespitter or KAX).

**Comment by seamus0riley** [comment] 2016-09-05 18:58
I was just thinking about this today. I wonder if there's a way to use a projector to generate a shape to block the line cast done during terrain checks which would effectively remove the vessel from the radar. Something based on the "stealthiness" of the plane vs distance to the radar source and it's power. I was messing around with it a little today as an add-on part. Obviously if you guys did it built into BDA it would be way better.

**Comment by TheDestroyer111** [comment] 2016-09-07 16:51
If I understand you right, @seamus0riley , then this would be far from realistic. To be reasonably realistic at least, it has to have a big performance impact, which would make it better to be a standalone. After giving it thought, I found out that if this was just a toggleable feature in standard BDA, it would be a pain for DMP servers, especially if live PvP was possible.

**Comment by seamus0riley** [comment] 2016-09-07 17:58
If I'm honest, I did not consider or test with dmp. However, since it's more designed to be on load, and then only on ship part change the performance effects on my system were negligible. Also the layer it moves it to is for disconnected parts, so if an item is registering as debris from another session on dmp it should transfer the settings yes?

**Comment by falc0nman** [comment] 2016-09-07 18:28
I missed the part about it being better as a standalone. Would you or your team object if I put something together as a standalone component then? I don't want to step on anyone's shoes.

**Comment by seamus0riley** [comment] 2016-09-07 18:30
Oops. Used the wrong account. 
I missed the part about it being better as a standalone. Would you or your team object if I put something together as a standalone component then? I don't want to step on anyone's shoes.

**Comment by DoctorDavinci** [comment] 2016-09-11 21:27
@seamus0riley - Not sure who you are asking about this as I am the first member of the BDAc team to reply to this issue

As for what you are asking, I see no problem with you moving forward with your idea as the team is open to new ideas as well as help from other modders. You could make it an addon for BDAc although I suggest speaking with the coding group of our team regarding this .....

They are:
@PapaJoesSoup 
@jrodrigv 
@SpannerMonkey

**Comment by TheDestroyer111** [comment] 2016-09-26 06:59
But what should such a system even be based on? What properties of a craft should it use to determine how well visible should a craft be to radar? It looks like carrying all BDArmory systems internally in cargo bays is the only condition for stealth that is (fairly) easy to implement. Any other thing that could potentially be used for RCS uses huge amounts of computing power. For "true" radar calculations, we need every single polygon to get radar reflection calculations several times (as radio waves sometimes reflect several times between surfaces, such as with certain types of engines or between the splitter plate of an intake and a fuselage). And all this has to be done several times per second as RCS is different from different angles. Also, a very important factor is material. In Korea, when Polikarpov Po-2 planes made night attacks on USAF bases, they were not detected on radar until they came enough close to drop bombs, because these planes were made mostly of wood, which doesn't affect radio waves so heavily. We also have radar absorbing paint being used on stealth aircraft. How do you think you can simulate different materials, or paint, when there are thousands of parts from different KSP mods, which are all made from various materials? I don't think it is possible to get into an agreement where every mod author adds material definitions into his own mod just because the BDA team is making a stealth mod that would still take so much computing power that most computers can't run KSP with it...

**Comment by KerbalPete** [comment] 2016-10-03 03:34
I would suggest for starters calculating a stealth constant based on the surface area of the vessel when it is loaded to minimize its performance impact, this should be calculated once and remain constant (perhaps updated for certain events). Then this should be modified by the distance from the radar. Then each radar should have a tolerance at which it detects a stealthy aircraft, with larger, better radar having a higher tolerance.

 I would remove the fixed detection range and replace it with this system within render distance. Then perhaps add a slider to adjust the sensitivity of the radar.

This opens a few doors for things like radar decoy systems to distract SAM sites.

I think this is achievable if a few assumptions are made and the system is simplistic.

Missiles in BDA are extremely accurate and without countermeasures are almost a certain kill.
I think the missile calculation updates can be reduced slightly in favor of better performance.
Flares also seem to be too effective.

**Comment by TheDestroyer111** [comment] 2016-10-04 18:00
@KerbalPete, this is roughly how radar cross section is currently calculated and implemented in BDArmory. The problem is that it's more of shape than cross section in reality - a B2 bomber directly above an enemy radar presents a huge cross section of itself to the radar with its large wings, but is still nearly invisible to radar as its shape is very specific.
Also, in reality missiles can be evaded by maneuvering and in BDA maneuvering usually doesn't help enough much, but most fighter jets are not just very maneuverable but can also go supersonic at low altitude, and thus go faster and farther than the missile.

**Comment by jrodrigv** [comment] 2016-11-15 17:48
I've reading all comments. And I don't think we are going to implement a more realistic radar system, mainly because of the performance impact. However, I'm not saying that at some point we can think a static algorithm that can evaluate a vessel stealth-ness when in VAB....but that would be a different feature.

**Comment by SpaceEnthusiast** [comment] 2017-06-06 11:32
I think I have an idea. Probably not a realistic way of simulating stealth, but here it goes. What if the player would have a slider menu in the editor that defines how stealth the plane is. I know it won't be realistic, but it still kinda works. Right?

**Comment by SpannerMonkey** [comment] 2017-06-06 12:41
> What if the player would have a slider menu in the editor that defines how stealth the plane is. I know it won't be realistic, but it still kinda works. Right?

I think that would be the worst of all possible options simply because everyone will push it to max and leave it there.
I think that until there's at least a glimpse of a possible future that allows for proper multiplayer use of BDAc stealth is just a waste of time.    It also seems a bit superfluous when it is so easy to beat a radar system and it's missiles by simply flying at very low altitudes

**Comment by SpaceEnthusiast** [comment] 2017-06-06 14:50
1. If the people want to put it on full, let them be. It takes away the fun, and if that's what they want, let them be.
2. This is simple. Which is why I like this idea.

**Comment by SpaceEnthusiast** [comment] 2017-06-06 14:51
Also, there is multiplayer. Look up darkmultiplayer (DMP)

**Comment by jrodrigv** [comment] 2018-04-29 11:27
Closing this issue because stealth mechanism has been already implemented @DoctorDavinci @TheDogKSP you may want to add more mechanism.

**Closed by jrodrigv** 2018-04-29 11:27 UTC
Labels: feature request
