### ISSUE TITLE
RBS 15

### ISSUE THREAD

**Issue by Skyer25** [PapaJoesSoup/BDArmory#16] opened 2016-08-07 08:49 UTC
The RBS-15 Cruise Missile after launch it flyes about 10 km then explodes due to overheating (Probably becouse FAR)

**Comment by TheDestroyer111** [comment] 2016-08-07 11:16
Did you target the missile properly with GPS coordinator? If no, then it's not strange that the missile flies a few kilometers and explodes midair (Also happens for me). If yes, then switch to the missile with "[" or "]" keys (or with the map view, but the first way to switch vessels is probably faster). Does the missile try to turn or keep up horizontal at all, or does it just fly a ballistic trajectory?

**Comment by Skyer25** [comment] 2016-08-07 12:44
yes i did target it, i tryed to fire 4 missiles at a time sometimes just 1 or 2 (from ground) and i did watch them everytime i shot from ksc island (or howewer the island is called) at the radar dish at ksc

**Comment by TheDestroyer111** [comment] 2016-08-07 15:46
Oh. I get it. This also happens for me. IDK why it happens. Most probably because these missiles are actually meant to be short range cruise missiles that fly no more than 10 km.
BTW that island you launched missiles from is called Old Airfield (crash into it and you'll see Collided or Crashed into Old Airfield when you press F3 button)

**Comment by Skyer25** [comment] 2016-08-07 16:15
Ok thanks.
its a bug with FAR that it heats up too much and then explodes due too atmosthere

**Comment by Skyer25** [comment] 2016-08-07 17:56
*//EDIT: Nope, this is a bug. Try launching the missile from a plane and following it closely until it hits the target, without switching to the missile. If you succeed, there is a chance the missile will fly for much longer than 10km from the launching point.*

yea but the missile is thought to be able to be launcht by ground and air and i want to launch it from ground

**Comment by TheDestroyer111** [comment] 2016-08-07 21:21
PapaJoesSoup pls help!
Well currently the only workarounds are firing at relatively close range, or using an aircraft.
Hmm... You mean that all the reentry effects and flames appear before the missile explodes? How fast does the missile go when it explodes? If the missile *EVER* goes faster than 500 m/s from a ground launch, something's definitely wrong.

**Comment by Skyer25** [comment] 2016-08-07 21:24
at the moment of explosion it goes 1000 km/h (i use FAR to change speeds) so still under mach 1. but in the F3 key it says overheatet even under mach 1 creates some heat so maybe the heat the missile it can take would help? i don't know

**Comment by TheDestroyer111** [comment] 2016-08-08 14:35
Nope. BDArmory's damage model is based on heating - If you hit an enemy craft, you might see that if any part of your opponent survived, some of them might be red hot. Explosions and bullet hits apply some heat to parts, and once a part gets too hot it explodes. If you ever check the F3 after destroying a craft, you will see some "XYZ exploded due to overheating".

**Comment by Skyer25** [comment] 2016-08-08 14:38
i know that bd is based on heat but why does it say then it exploded of overheating?

**Comment by jrodrigv** [comment] 2016-08-08 14:57
@Skyer25 Did you try to do exactly the same without FAR? It would be great to see if you can reproduce this without FAR.

Regarding the 10 km and the heating. I think every BDArmory missile has a max distance, altitude range and even a max time flying. And when this happens the missile is auto-detonated and this means that it current temperature is increased to the maximum temperature +1, so it explodes due to overheating :)

**Comment by Skyer25** [comment] 2016-08-08 15:23
*Try launching the missile from a plane and following it closely until it hits the target, without switching to the missile. If you succeed, there is a chance the missile will fly for much longer than 10km from the launching point.*

**Comment by TheDestroyer111** [comment] 2016-08-08 15:23
> i know that bd is based on heat but why does it say then it exploded of overheating?

It says exploded of overheating because the missile's explosion heated up the missile itself, making it explode due to overheating

**Comment by jrodrigv** [comment] 2016-09-02 21:13
Closing this. I think the reason is the auto-detonation of the missile when is missed or there is no progress of the missile.

**Closed by jrodrigv** 2016-09-02 21:13 UTC
