### ISSUE TITLE
RWR will not be triggered by oposing team radar if it has been manually switched off by the user

### ISSUE THREAD

**Issue by DoctorDavinci** [PapaJoesSoup/BDArmory#411] opened 2017-12-15 02:08 UTC
##### ISSUE TYPE
 - Bug Report   (Something is broken)

##### KSP and BDA Version

KSP v1.3.0

BDAC v1.1 Public Beta

##### OS / ENVIRONMENT
Windows 10

##### SUMMARY
If a user manually opens and closes the RWR it will not automatically engage when detected by the opposing teams radar

##### STEPS TO REPRODUCE
- Place a Jernas with AIM-120's at the island airport (Team B)
- Launch an aircraft with a radar on it (Team A)
- While taking off open the BDAc window, click Modules and open the RWR
- Close the RWR and proceed to fly towards the Jernas at the island airport
- The Jernas radar will detect the aircraft and launch AIM-120's at it but the RWR will not be triggered upon being detected by the Jernas

In the video below I manually opened the RWR to reposition it and then closed it during take off. Later on you will see me launch 4 HARM's at the enemy in the Mountain Pass East of the KSC, at this time I hadn't realized that the RWR was not open which is why they didn't acquire a target

##### Log Files
https://www.dropbox.com/s/yvj5sy95sof65qs/Test%20Logs%20001%20%5B12.14.17%5D.zip?dl=0

##### VIDEO
https://www.youtube.com/watch?v=EodYluN-sWo

**Comment by TheDogKSP** [comment] 2017-12-15 12:33
Doc, you are a producer of quality issues :)
I take it and will investigate, hopefully just a quick fix

**Comment by TheDogKSP** [comment] 2017-12-21 14:24
mmhhh, according to the code it is actually "by design", there is a check for "rwrEnabled".

What whould be your expected behaviour if the RWR window is closed (hence rwr disabled)?
A) incoming radar ping audio only?
B) rwr window will automatically pop open? could be a bit annoying...
C) AntiRadar missiles still able to acquire target?

I presume you'd expect a) and c), right?

**Comment by DoctorDavinci** [comment] 2017-12-21 22:18
Actually I would expect all 3

What led me to this obscure detail is that option b is the default at launch, meaning the rwr is on a sort of standby mode at launch and pops open when your craft is detected by enemy radar. 

In the above scenario I wanted the rwr window to be located elsewhere on the screen (screen gets cluttered even in 1080p) so I opened it, moved it and then closed it again ... what I would expect is the rwr would go back to the default 'standby' mode and be triggered on radar detection

This also brings to mind having a sort of silencing switch to minimize the window to the edge of the screen ..... related to https://github.com/PapaJoesSoup/BDArmory/issues/410

**Comment by PapaJoesSoup** [comment] 2018-05-27 02:03
Review of the code revealed that rwrEnabled was being used for 2 purposes first to enable /disable RWR operation, and second to show/hide the RWR display.

If a radar is installed, RWR should always be enabled, so that detection can occur even if the window is closed. (expected behavior).
Open and closing the window should NOT affect the RWR operation.

Corrected in Support Branch.  Will be included with next release.

**Closed by PapaJoesSoup** 2018-05-27 02:03 UTC
Labels: bug
