### ISSUE TITLE
Investigation for the black kraken and the "Look rotation viewing vector is zero"

### ISSUE THREAD

**Issue by Nerfclasher** [PapaJoesSoup/BDArmory#5] opened 2016-08-01 18:28 UTC
I'm still running into a bug with the PAC turret when leaving the craft then coming back to it and everything turns black and it spams the logs with this forever 

[LOG 12:00:15.338] Look rotation viewing vector is zero

and here are the links to the logs 

[](https://www.dropbox.com/s/a0puwsiyd04urej/output_log.txt?dl=0)

[](https://www.dropbox.com/s/9nk7o4yyprcdgk9/KSP.log?dl=0)
save
[](https://www.dropbox.com/sh/xgf5judy2t9ijm4/AACA4O6_83LJRzH6bz4DpB66a?dl=0)
reproduce steps
take the premade craft and fire some missiles don't deselect the missiles
leave the craft and return in a few seconds the screen will go black

**Comment by SpannerMonkey** [comment] 2016-08-02 02:42
This may need an export of the model to check transform positions, I believe the pac 3 turret uses look and constraintFX modules to position and animate the pitch ram. I can't think of anything else that could produce such an error, unless the WM needs some king of look vector(don't remember seeing that in the source though)

**Comment by jrodrigv** [comment] 2016-08-02 22:01
Shall we change the name of this issue? I think a lot of people is getting from completely different scenarios.

@PapaJoesSoup I'd say this one can be a top priority issue.

**Comment by jrodrigv** [comment] 2016-08-04 20:20
We need to investigate the root cause of this issue. I'm not completely sure that this is due to BDA. 
I've found this:
http://forum.kerbalspaceprogram.com/index.php?/topic/107057-look-rotation-viewing-vector-is-zero-gt-black-screen/

I'll add traces to the code to see if the "Look rotation viewing vector is zero" is generated by BDA.

**Comment by PapaJoesSoup** [comment] 2016-08-04 20:32
I've been seeing reports of interesting issues in the modded install forum.  I've requested they follow our troubleshooting steps on the OP, but no one has provided any logs to work with.  Without any kind of log, it is very difficult to troubleshoot.   I suggest the original author of the issue provide something in the way of data for us to start from.

**Comment by SpannerMonkey** [comment] 2016-08-08 18:08
Hi, I've just been bug hunting for another unrelated to BDA issue mod problem , it's not even a weapons mod and the same error is causing all the issues there too. I also did some digging and although it has cropped up from time to time i cannot find anyone who can comprehensively state what causes it.  But i found this and if you read the thread, once he carried out the fix mentioned  there. the error was no longer being reported
[http://forum.kerbalspaceprogram.com/index.php?/topic/138100-parts-shaders-replacement-pbr-wip-release/&do=findComment&comment=2556804](url)
You can find cases of this totally unrelated to BDAc going back years literally

**Comment by PapaJoesSoup** [comment] 2016-08-08 20:09
We definitely are using shaders.  Can't open the link via mobile but will read

**Comment by jrodrigv** [comment] 2016-11-06 20:49
Closing this issue. It is not reproducible anymore

**Closed by jrodrigv** 2016-11-06 20:49 UTC
Labels: Need Confirmation

**Comment by Nerfclasher** [comment] 2016-11-06 21:07
Going to check
