### ISSUE TITLE
[Request] Multiple weapons on a turret

### ISSUE THREAD

**Issue by harpwner** [PapaJoesSoup/BDArmory#12] opened 2016-08-05 02:46 UTC
Turrets with multiple weapons (such as my LAV-AD turret being withheld from my addon) seem to fight themselves. By this I mean I have made a turret that has a gau gatling gun and a set of stinger pods on the same platform. They use the same transforms and turret setup, though I have tried separating them by both Turret ID and 2 separate turret modules, but this has not worked. I am still looking for a workaround, but the current situation seems that the GAU and Stinger fight each other when aiming as one of them is deactivated and as such wants to be in the idle position, while the other should be free moving. This causes stuttering and lockups in the aiming process and breaks the part in general.

**Comment by Nerfclasher** [comment] 2016-08-05 02:52
Are you able to give me logs so we can support you I understand your frustration about Bdarmory not letting you two guns as one turret

**Comment by PapaJoesSoup** [comment] 2016-08-05 03:13
Harpwner, I'll begin looking at the code now.  is there any way to replicate the issue with existing parts?  Or would it be a good idea for us to have the parts to test with?  Just want to be sure we address it properly.

**Comment by PapaJoesSoup** [comment] 2016-08-05 03:59
Looks like in the code the fact that you are using the same transforms is the cause.  I'm not up to speed on the transforms yet, but is it possible to give each turret module a separate transforms?

**Comment by harpwner** [comment] 2016-08-05 07:22
Sorry for the time it took for me to reply, I wasn't notified very well O_O
The idea of giving the turret modules 2 separate transforms had occured to me once I had this up as a workaround, however it is too late for me to test right now. As for now I am aware of no logs but I do know the issue can be replicated if I simply give you the part in question. If you do need it tell me and I'll respond in the morning.

**Comment by PapaJoesSoup** [comment] 2016-08-05 16:02
Sorry to the change in labeling type.  as stated in the forums. BahamutoD had already replied to a similar issue and noted that the code does not support it at this time.  This is also in line with a similar request to have multiple targeting.  The current architecture of BDArmory does not support it at this time.  It will require significant refactoring to make such a feature possible.,

So We are changing this to a feature request.  I know the feature is in demand, so as part of the "grand Vision" for BDArmory, we will definitely want to add this capability.

**Comment by harpwner** [comment] 2016-08-05 17:59
I changed the title to reflect this and I'm going to attempt said workaround. Thanks for your consideration and I do understand why it cannot be addressed so soon.

**Comment by PapaJoesSoup** [comment] 2016-08-18 21:39
A work around has been determined, by ensuring that each turret has its own transforms.

Closing Issue.

**Closed by PapaJoesSoup** 2016-08-18 21:39 UTC
Labels: enhancement
