### ISSUE TITLE
Crazy aero FX and AI deselecting radar signature

### ISSUE THREAD

**Issue by Deathpuff12** [PapaJoesSoup/BDArmory#155] opened 2017-03-20 05:34 UTC
So the first issue is these crazy aero FX (the ones you get when you're going really fast). Whenever I'm testing/playing with my creations, I like to occasionally switch to the missiles and watch them fly to their target. But, a bad bug happens that causes huge fps drops. It's hard to explain, so I made a video for it:
https://youtu.be/5VDrXEW6ePA

Next issue is the AI and the radar. I've been messing with tanks and stuff, and I have a land vehicle set up that launches radar missiles vertically, using a TWS locking radar (this problem also occurs with the Jernas missile turret) to target aircraft. However, when it's in guard mode, the AI selects the target in the radar, launches a missile, and then deselects the target after a few seconds. This never gives the missile enough time to lock on by itself (the radar missiles only actively home in on targets in the terminal phase), and it misses 100% of the time.

**Comment by jrodrigv** [comment] 2017-03-20 05:47
Hi! So regarding the first one. I recommend to always disable AeroFx when playing BDArmory,ñ. Missiles will always trigger aero effects because they are flying quite fast. Besides this, there is also a problem with the 'emitters', they are triggering fx too

**Comment by Deathpuff12** [comment] 2017-03-20 06:36
Yeah, I just thought I'd write that because I haven't seen it anywhere else.
Also, about the radar problem: I've done some more testing and it seems to be completely random. I've tried at different altitudes and with different shapes and sizes of aircraft. Sometimes it deselects them, and sometimes it keeps them selected all the way up until they're destroyed. Sometimes it deselects them and the missile still hits, and sometimes it doesn't.
Anyways, I think the AI should always keep a target selected on radar until it is destroyed or has no weapon manager. Otherwise, the missile will occasionally be completely wasted, missing by a kilometer or more.

**Comment by jrodrigv** [comment] 2017-03-20 06:43
Would you mind to send me the craft file with the missile launcher? Or a
video with the scenario? I will try to reproduce it locally.

Thanks!

**Comment by Deathpuff12** [comment] 2017-03-20 07:48
Yeah, sure. Here's the link to the KerbalX page: https://kerbalx.com/Deathpuff12/AA-29-Wolverine

**Comment by jrodrigv** [comment] 2017-03-21 19:41
I've been trying to reproduce this, but I think it works as expected. The only time I see AIM-120 missing the target (with deselecting) was when the target aircraft fires its chaff/countermeasures.

**Comment by Guard13007** [comment] 2017-03-23 03:58
@Deathpuff12 Missiles can be fooled by a plane quite soon after being launched with the way BD Armory works, are you sure it isn't as @jrodrigv has said and the plane is launching countermeasures? Try it without using countermeasures.

**Comment by Deathpuff12** [comment] 2017-03-24 03:23
Sorry about the delay. I've tested it more without the chaff and it seems that the issue was me :(
However, one thing does still irritate me. Whenever I lock the target manually, the missile isn't affected by the aforementioned problem.
Anyhow, I think there should be some indicator that the missile/radar has lost the lock. Because as it is now, it just looks like the guard mode isn't working properly.

**Comment by jrodrigv** [comment] 2017-03-24 16:52
Thanks for your feedback. I will close this issue then.

**Closed by jrodrigv** 2017-03-24 16:52 UTC
