### ISSUE TITLE
Rotary missile mount doesn't allow AI to fire

### ISSUE THREAD

**Issue by DoctorDavinci** [PapaJoesSoup/BDArmory#28] opened 2016-08-15 22:14 UTC
Having issues with the rotary mount ... Seems the AI will not launch a missile from a cargo bay if using the rotary mount

**Comment by TheDestroyer111** [comment] 2016-08-16 07:06
The AI won't fire from cargo bays at all... You may have no problems with normal cargo bays, but many people do.

**Comment by Nerfclasher** [comment] 2016-08-16 23:17
https://github.com/BahamutoD/BDArmory/issues/36

**Comment by gomker** [comment] 2016-08-19 19:44
AI on my craft are able to fire from cargo bay with the rotary rack with the latest versions at this time.  My vessel fired AIM120, Sidewinder and JDAM

I will note that sometimes the AI can get confused, the cargo bay doors open and close frequently as target moves into and out of gun range. I wonder if this may have something to do with it.

**Comment by TheDestroyer111** [comment] 2016-08-20 08:11
This issue looks like something environment-specific.
My environment is OSX 10.9.4, KSP 1.1.0 with some other mods too (but no bda extensions).

**Comment by DoctorDavinci** [comment] 2016-08-20 15:40
Would you be able to list the mods you are using so we can test the same KSP setup on other systems?

**Comment by TheDestroyer111** [comment] 2016-08-21 08:26
Analog Control 1.6.2
B9 Aerospace 6.1.1
BDArmory 0.11.1.2
DarkMultiPlayer 0.2.3.1
Dynamic Deflection 1.2.1 (I think it is a junk mod, because it is supposed to help Pilot Assistant at varying altitudes and speeds, but it doesn't seem to)
Firespitter 7.2.3
FSHangarExtender 3.3 (yes I know this is for a different version of KSP, but it doesn't cause problems, and I installed it after testing missiles in cargo bays)
KAS 0.5.9
KAX 2.6.1
Kerbal Engineer Redux for KSP 1.1.1.0 (I know it's for one version higher, but it doesn't cause problems)
HyperEdit 1.5
KIS 1.2.12
All three parts of Large Boat Parts Pack (when you download the mod, you get three folders which can be installed independently, although they work nicely with each other)
MechJeb2 2.5.7.0
MouseAimFlight 1.0.1
Pilot Assistant 1.12.5
Squad (the stock game, it's not a mod actually, version 1.1.0)
Throttle Controlled Avionics 3.1.0 for KSP 1.1.2 (another junk mod, it's broken for some reason, probably because I don't have MM)
VesselMover 1.5

As you can see, I don't have FAR (some people think this bug is caused by FAR, but it cannot, and also I don't even have FAR).
As you may see too, I don't have ModuleManager. I know I have some mods which are said to require MM, but aside from TCA simply not working, not installing MM didn't cause any issues with any mods that are said to require it. Also, not using MM *may* have saved me from posting in the technical support section of the KSP forums. (My entire 1.0.5 game was once seriously broken due to MM)

**Comment by DoctorDavinci** [comment] 2016-08-21 15:39
@TheDestroyer111 - First off, by using mods that do require MM and not using MM means that there are configs that haven't been loaded in order for the mods to work properly

Second off, you apparently are playing 1.1.0 as you stated on the forums, and I quote:
> I am playing on 1.1.0 myself because I'm too lazy to find two hours (my internet is kinda slow) when my internet manages to not crash so that I can download the new version. (stupid internet provider!) Also, the other reason is that I still don't know if 1.1.3 is stable at all. I think it's more worth it to wait for 1.2, but TBH hell knows if it is. 

There has been subtle code changes done between 1.1.0 to 1.1.1 to 1.1.2 to 1.1.3 and there in lies your problem ... BDAc is compiled for 1.1.3 and it is where we at the BDAc development team have started our support

Update your KSP to 1.1.3 and BDAc will work, if not we can help you then ... if you are unable to update to 1.1.3 there is little that we can do to help

**Comment by gomker** [comment] 2016-10-07 02:03
Closing as this appears to be not applicable to current version

**Closed by gomker** 2016-10-07 02:03 UTC
