### ISSUE TITLE
Radar Data Link does not persist in reload 

### ISSUE THREAD

**Issue by gomker** [PapaJoesSoup/BDArmory#241] opened 2017-07-16 15:59 UTC
Data links between radars are not persistent

**Comment by TheDogKSP** [comment] 2017-10-29 18:08
FIXED in next release
(tested, cannot reproduce problem with current dev branch)

**Comment by TheDogKSP** [comment] 2017-11-04 15:29
v1.0.0 released, closing this issue

**Closed by TheDogKSP** 2017-11-04 15:29 UTC
Labels: bug, P3, Targeting
