### ISSUE TITLE
[1.7]ksp suddenly closes when picking mirror attached hydra 70 weapon while in midflight

### ISSUE THREAD

**Issue by tonimark** [PapaJoesSoup/BDArmory#688] opened 2019-05-03 14:27 UTC
When reporting issues please provide the following information:
so I built up a fighting helicopter (mil mi 24) and I equip it with some weapons including hydra 70 rockets 
[See this for more information on reporting issues for KSP Mods](http://forum.kerbalspaceprogram.com/?showtopic=83212)ok

[See the Original Forum Post (OP) for additional info](http://forum.kerbalspaceprogram.com/?showtopic=155014)ok

##### ISSUE TYPE: the game suddenly closes when picking weapon inflight(sudden crash)
 - Bug Report   (Something is broken)

##### KSP and BDA Version

```ksp versions 1.7

```bda versions 1.3.0.0_050120192355

##### OS / ENVIRONMENT
a normal enviroment 
windows 10 pro  build 1809

##### SUMMARY
<!-- Explain the problem briefly -->
when I click on hydra rocket 70 while inflight the game crashes 
##### STEPS TO REPRODUCE
<!--1.build a helicopter with 1(2) mirror attached hydra 70 rocket 
2.launch the vessel and inflight pick the hydra 70 rocket from the bdarmory menu
-->


##### Log Files
<!-- /KSP Directory/KSP.log -->
[KSP.log](https://github.com/PapaJoesSoup/BDArmory/files/3142298/KSP.log)

<!-- /KSP Directory/KSP_x64_Data/Output.txt -->not found
<!-- You can also paste gist.github.com links for larger files -->

**Comment by jrodrigv** [comment] 2019-05-04 10:25
Please before reporting BDA issues ensure that you don't have any other mods apart from BDA and its dependencies.
I have been checking your logs and you have dozens of mods and some of them seems to be causing exceptions like :

[EXC 17:15:29.590] DllNotFoundException: SDL2.dll
	KSPAdvancedFlyByWire.SDLController.InitializeSDL ()
	KSPAdvancedFlyByWire.SDLController.SDLUpdateState ()
	KSPAdvancedFlyByWire.AdvancedFlyByWire.Update ()

I'm going to close this issue, please open a a new one if you can reproduce it using just BDArmory and its dependencies.

**Closed by jrodrigv** 2019-05-04 10:25 UTC
