### ISSUE TITLE
vulcan and turret bullet textures not working

### ISSUE THREAD

**Issue by KERBALZ** [PapaJoesSoup/BDArmory#78] opened 2016-11-05 03:00 UTC
I set up a turret, put it on guard mode, and the bullets were pink. not only that but every bullet was pink, from every gun! goalkeeper, browning, vulcan, etc.

**Comment by gomker** [comment] 2016-11-05 03:13
This appears to be a duplicate of Issue #73 - There are known issues with Shaders being incorrect for OSX and Linux - this is being addressed.

**Closed by gomker** 2016-11-05 03:13 UTC
Labels: duplicate
