### ISSUE TITLE
20 mm not compatible with other guns

### ISSUE THREAD

**Issue by TheDestroyer111** [PapaJoesSoup/BDArmory#17] opened 2016-08-07 12:10 UTC
If both a 20mm gun (either stationary and turret) and any gun in different calliber are put on the same craft, the second gun will fire properly, but the 20mm will only make a sound and not fire at all (or fire in a kinda semi-auto mode).

**Comment by gomker** [comment] 2016-08-07 20:01
Have you checked to make sure you have both ammo types available.
Also I have seen this issue occur with Guard Mode being enabled, it will only select one gun and override your manual selection, firing the gun once before switching.

I created a test vessel with all guns and was able to fire one at a time and cycle through and also all at once after toggling each on.

![screenshot77](https://cloud.githubusercontent.com/assets/3577339/17464938/8aa7dd24-5caf-11e6-9aff-5d8b4258cf0c.png)

**Comment by TheDestroyer111** [comment] 2016-08-07 21:12
LOL of course i have ammo for both types of guns. Also, if I didn't have ammo, it would never fire, even in a kinda-semi-auto mode, and it wouldn't make a firing sound.

**Comment by gomker** [comment] 2016-08-07 22:08
Don't know what to tell you. I can get it to work with latest BDA - you want a copy of this craft to see if it works?

**Comment by TheDestroyer111** [comment] 2016-08-08 09:39
I think I should update my BDArmory to the latest version. This could fix problems with 20mm, and would fix the dreaded PAC lag and hydra sound issues.

**Comment by jrodrigv** [comment] 2016-08-08 14:40
@TheDestroyer111 Can you create a craft with stock parts and attach the .craft file here, so I can debug it :)

**Comment by TheDestroyer111** [comment] 2016-08-08 15:16
I think it's a little pointless since you can just attach 20mm and another gun to something, but here you are: 
[MiG-15 (B9 engine).txt](https://github.com/PapaJoesSoup/BDArmory/files/407119/MiG-15.B9.engine.txt)
(Unfortunately Github doesn't accept a .craft extension and I have to use .txt, so you should change it to .craft)

**Comment by gomker** [comment] 2016-08-10 16:13
I am not able to reproduce this issue in a new vessel.  There are some reports of old craft displaying this problem.

**Comment by TheDestroyer111** [comment] 2016-08-11 08:17
The craft I submitted is from BDArmory 0.11.x so it's not probable for the bug to be caused by an old BDA version, but I somehow forgot to check whether this happens on entirely new craft made on a the newest BDA version... no, issue still exists.

**Comment by TheDestroyer111** [comment] 2016-08-14 20:03
For some reason, I never tested this with 30mm before, but I just did. Well it appears that the 30mm is incompatible with 50cal too. (a gau-8 has the same problem when the craft also has Browning guns)

**Comment by Nerfclasher** [comment] 2016-08-23 14:49
I tested it on a install with only bdarmory latest version but found no bugs sorry can't help

**Comment by TheDestroyer111** [comment] 2016-08-23 15:08
50 mm? There is no 50mm in BDArmory! Did you mean 50cal, or the cannon caliber (either 105 or 120mm, because BDA has two guns which use the same cannon ammunition but are different in reality)?
Hmm... What is your environment of BDA? I told it in another issue here so I don't wanna repeat :P

**Comment by gomker** [comment] 2016-10-07 02:17
Closing as this appears to be not applicable to current version

Re: issue 28

**Closed by gomker** 2016-10-07 02:17 UTC
