### ISSUE TITLE
Reload sound missing

### ISSUE THREAD

**Issue by Wraith977** [PapaJoesSoup/BDArmory#39] opened 2016-08-30 16:31 UTC
As reported on page 18 of the forum thread: The M1 Abrams turret and the M102 Howitzer (maybe more) are supposed to have a reload audio but they don't seem to be playing it at all. The path still seems correct, "reloadAudioPath = BDArmory/Parts/m1Abrams/sounds/reload".

**Comment by DoctorDavinci** [comment] 2016-08-31 00:13
Confirmed ... No reload sound is heard when firing either the M1 Abrams Turret or the M102 Howitzer

https://youtu.be/FIGdqgLMyrA

**Comment by PapaJoesSoup** [comment] 2016-09-01 23:06
Do you have an output.log for this test?  THere may be an error in the log I can review...

**Comment by PapaJoesSoup** [comment] 2016-09-02 00:31
Found the issue.  Now to see if the fix is worse than the bug...

**Comment by DoctorDavinci** [comment] 2016-09-03 20:13
No, I didn't think to make a copy of it as it gets rewritten every time I run a new test ... I'll be sure to save that information moving forward

**Comment by PapaJoesSoup** [comment] 2016-09-04 03:44
This issue was caused by the update to KSP 1.1.  BahamutoD disabled reloadbar and Heatbar, due to a missing object.  I located the change and added code to create the icon in the module OnStart method.
Now, the Icon is back in the staging area (was gone), and the reload bar, heat bar and reload sounds work.  WIll be included in the next release.

**Closed by PapaJoesSoup** 2016-09-04 03:44 UTC
Labels: bug

**Comment by jrodrigv** [comment] 2016-09-04 08:53
Nice one :)
