### ISSUE TITLE
Game crashes when adjusting the Rotary Bomb Rack

### ISSUE THREAD

**Issue by Schmitty548** [PapaJoesSoup/BDArmory#76] opened 2016-11-03 22:20 UTC
I've been able to replicate it, and read on the forum someone else that had this problem. Couldn't find the thread here so I thought i'd start one. Adjusting the Rotary Bomb Rack's height and length has crashed my game, haven't tried the other values. Ive supplied my crash reports, if something went wrong uploading the files just let me know, I couldn't get it to work right

[output_log.txt](https://github.com/PapaJoesSoup/BDArmory/files/570210/output_log.txt)

[output_log.txt](https://github.com/PapaJoesSoup/BDArmory/files/570211/output_log.txt)

**Comment by SpannerMonkey** [comment] 2016-11-03 23:12
HI , I have attempted to replicate your issue and have been unsuccessful,  all tests changing sizes number of rails etc  did not provoke a crash.  Could you retry and on crash get a copy of your KSP.log as well as the output_log, linked here,  Thanks.

**Comment by Schmitty548** [comment] 2016-11-04 00:53
Hello, I hope I have supplied the correct file, if not, I will change it. I do have many other mods installed, and the fact you were unable to replicate it, but someone else was, makes me believe its a compatibility issue, not really the fault of the mod crew


[New Text Document.txt](https://github.com/PapaJoesSoup/BDArmory/files/570400/New.Text.Document.txt)

**Comment by Thorimus** [comment] 2016-11-04 21:51
I'm getting this issue as well and am able to reproduce it. Happens when right-clicking to close the rail editing window after editing it.

[output_log.txt](https://github.com/PapaJoesSoup/BDArmory/files/572716/output_log.txt)

**Comment by DoctorDavinci** [comment] 2016-11-05 01:12
I have looked through the log files and both are throwing exceptions from other mods

There is one mod in common both users have, KAS v0.6 ... This was released October 4th and KSP 1.2 was released October 11th

Perhaps a mod conflict or maybe using mods that are compiled for the 1.2 pre-release could be the culprit as I am unable to replicate the issue in a clean KSP v1.2.1 install with the only mod being BDAc v0.11.1.5

**Comment by Thorimus** [comment] 2016-11-05 11:05
I will try again tonight without KAS and see if it works.

**Comment by Schmitty548** [comment] 2016-11-05 13:06
I uninstalled KAS and still receive the crash. This is just down to finding the incompatibility

**Comment by Exelio** [comment] 2016-11-05 15:28
I'm getting the exact same issue and it happens whenever you adjust any of the settings on the Rotary Bomb Rail. just tested this with no mods except BD Armory of course and it still causes KSP to crash...

Crash log:
[output_log.txt](https://github.com/PapaJoesSoup/BDArmory/files/573310/output_log.txt)

**Comment by jrodrigv** [comment] 2016-11-05 20:13
I can confirm this issue. Playing with the different options a bit and right-clicking...and boom!

**Comment by gomker** [comment] 2016-11-05 22:24
Confirmed - Seems to occur after you edit the rail then go back to right click. I wonder if settings are not getting saved correctly after edit. 
No luck capturing further details with VS Debug

**Comment by Thorimus** [comment] 2016-11-06 11:52
Uninstalled KAS 0.6.0, KAS 1.0, and KIS - still crashes.
[output_log.txt](https://github.com/PapaJoesSoup/BDArmory/files/573792/output_log.txt)

**Comment by gomker** [comment] 2016-11-06 15:38
Hello All - as this message is a Memory exception from KSP the logs will not help in capturing more data on this.  We are debugging this as much as we can at the moment however, be aware that Memory exceptions are extremely difficult to track down, even with access to original source (which we do not have as this is a Game/KSP exception) 

Thank you for your input, at this time no more logs are needed as we troubleshoot further.

**Comment by Exelio** [comment] 2016-11-07 13:11
I'm not sure if this is of any help but I'm a programmer myself and when I looked at the error log mine created it seemed to me as if it has something to do with an attempt to call an event that's not present, or a missing animation/model of some sorts... Like I said, not sure if this might help you guys ahead a bit, either how I wish you guys the best of luck tracing this bug :)

**Comment by stasikos** [comment] 2016-11-26 00:49
Okay, done some research, checked some "recipes" to KSP crash on right click in general:
I doesn't crash when part-highlighting (Hightlight FX) is disabled in game settings. Once enabled back it starts crashing again. 
That's why some of you can't reproduce it.

**Comment by Deluki** [comment] 2016-12-02 11:57
Same Issue
[output_log.txt](https://github.com/PapaJoesSoup/BDArmory/files/627077/output_log.txt)

**Comment by gomker** [comment] 2016-12-02 21:47
@stasikos  I can confirm that turning off Highlight FX seems to keep the problem from occuring.
I was also having other FX related crashes that Highlight FX addressed. This seems to be a larger KSP issue that may be somewhat known

http://forum.kerbalspaceprogram.com/index.php?/topic/151923-frequent-crashing-in-121-solutions/

**Comment by jrodrigv** [comment] 2016-12-16 20:38
With KSP 1.2.2 this is issue has gone. Closing it.

**Closed by jrodrigv** 2016-12-16 20:38 UTC
Labels: 1.2, bug
