### ISSUE TITLE
TWR Radars doesnt work in guard mode.

### ISSUE THREAD

**Issue by LtRyan** [PapaJoesSoup/BDArmory#372] opened 2017-11-21 18:02 UTC
##### ISSUE TYPE
- Bug Report   (Something is broken)
##### KSP and BDA Version
latest

##### OS / ENVIRONMENT
Win7

##### SUMMARY
All radars with tracking capabilitie can't lock and hold lock in guarding mode

##### STEPS TO REPRODUCE
-place a Radar with locking capabilitie
-activate the modules and guard mode
-start a hostile aircraft
-radar wont lock on to it

##### Log Files

[output_log.txt](https://github.com/PapaJoesSoup/BDArmory/files/1492449/output_log.txt)

**Comment by TheDogKSP** [comment] 2017-11-21 19:52
- Uninstall BDALoadedVesselSwitcher. It is part of BDA, this separate outdated mod is conflicting with BDA.
- the log is unfortunately not useful - please enable debug labels in BDA options, then take another pass
- could you also post your craft and scenario sfs?

**Comment by LtRyan** [comment] 2017-11-21 20:36
Gonna try it without vesselswitcher.
I dont use any special craf or scenario. Just builded one from scratch

**Comment by LtRyan** [comment] 2017-11-21 20:54
Well that was weird..
i uninstalled it but still could use the VS button in weapon manager and used it
[output_log.txt](https://github.com/PapaJoesSoup/BDArmory/files/1492915/output_log.txt)

**Comment by DoctorDavinci** [comment] 2017-11-22 04:57
Vessel Switcher was integrated into BDAc a couple versions ago

**Comment by TheDogKSP** [comment] 2017-11-22 07:13
What radar was attempting to lock? The stock bda test?
At what range was the lock attempted?
What is the stealth performance of the craft vs that radar, at what range is it lockable according to the rcs analysis?

**Comment by TheDogKSP** [comment] 2017-11-22 08:15
And please explain the scenario a bit:
you have 3 SAM vessels around from what I can see.
The "SAM-EW" is clearly seeing your drone, but the problem is not radar locking - the problem is that it does not have any weapons that can be used versus the drone, thus it wont lock it. That behaviour is not a bug.
So, which vessel has what kind of weapons configured, and what would you expect to happen (who should engage with which weapon at what range)?

**Comment by LtRyan** [comment] 2017-11-22 18:19
Ok first of all I tested it almost with every radar. Stock version and modded version by f.e. SMA
The drone is a simple drone like a reaper.
I tried to lock on it on every distance and altitude.
The thing is as soon i manual lock on to the target the Radar guard mode unlocks it.

Well I allways builded big SAM sites with the normal BD like this. EW, TR, CIWS, LU. This worked in the past.

**Comment by LtRyan** [comment] 2017-11-22 18:44
So I found a semi solution. I just added to my TR a downsidefacing A2A missile and now it almost holds track to the target that my LU can shoot it down.

**Comment by TheDogKSP** [comment] 2017-12-19 08:34
No more info provided, closing

**Closed by TheDogKSP** 2017-12-19 08:34 UTC
Labels: Need More Info, Support
