### ISSUE TITLE
AI controlled missiles in cargo bays don't fire.

### ISSUE THREAD

**Issue by Alphasus** [PapaJoesSoup/BDArmory#15] opened 2016-08-07 02:33 UTC
LOG:https://drive.google.com/open?id=0B3IvrPbGhZWFem9HVXR2QmVKZVE
GameData folder: https://drive.google.com/open?id=0B3IvrPbGhZWFc0w0M25BT1VHZEE
My mods:
B9 Aerospace 6.1.2
BDArmory 0.11.1.2
Environmental Visual Enhancements 1.1-1
Scatterer v0.0247
VesselMover 1.5.1
ModuleManager 2.6.5
Hyperedit
Reproduction Steps:
1. Create 2 different aircraft with B9 parts, a weapons manager, and an AI pilot system. 
2. The weapons I used were 4 AMRAAM missiles in cargo bays, per craft. Mark the missiles as In Cargo Bay=True.
3. Use HyperEdit to move them apart(will explain in separate report).
4. Engage engines on both crafts, with throttle at 0 and brakes enabled. Engage Guard Mode on stock settings.
5. Turn AI onto standby mode, and then enable AI on both aircraft.
6. After making sure that they are on different teams, watch as they do not fire at each other, even if you enable competition mode with competition mode's 8000m defaults.

**Comment by TheDestroyer111** [comment] 2016-08-07 11:58
Confirmed also on stock cargo bays. For reasons unknown to me, guard mode doesn't seem to fire missiles from cargo bays at all. It obtains radar lock and selects the missiles in the weapon manager but doesn't fire them. There are, however, several possible workarounds:
- Fire the missiles manually. guard mode will lock and arm the missiles, just won't fire.
- Don't mount the missiles in cargo bays. You can still mount them on the belly which is roughly the same as in cargo bays, the missiles don't create much drag (At least with stock aero, I don't know what about FAR)

**Comment by Alphasus** [comment] 2016-08-07 12:43
This is all sort of necessary for a tournament I am running involving BDArmory. The fighters have to be stealth, so most weapons must be stored in cargo bays. **That** is why I need working cargo bays, and automatically fired missiles(and I prefer if competition mode works because it makes this easier, but not significantly so). The workarounds invalidate the idea of the tournament that I'm running.

**Comment by DoctorDavinci** [comment] 2016-08-07 14:40
Question - how were they mounted and was there anything obstructing the nose of the missiles

**Comment by Alphasus** [comment] 2016-08-07 14:54
They were mounted on a rotary rack used for bombs and missiles. It had 4 rails. The missile heads were not clipped, but fuselages were in front of the cargo bay. So the missiles had something in front of them, but weren't clipped. When manually dropped, they exit the bay safely.

**Comment by Nerfclasher** [comment] 2016-08-07 15:00
There is a bug with rotary rack if you jettisoned the weapons so did you jettisoned the bombs or missiles

**Comment by Alphasus** [comment] 2016-08-07 16:01
No, I didn't jettison them. I fired the weapons manually via right click.

**Comment by Alphasus** [comment] 2016-08-07 16:02
No, I didn't jettison them. I fired the weapons manually via right click to test clearance.

**Comment by gomker** [comment] 2016-08-07 19:50
@Alphasus  My AI vessels have been firing missiles from cargo bays for some time. I thought it may be an issue with the latest up date and I ran some tests just now with setup as follows

- Loaded F-22 on runway
- Used Vessel Mover to spawn 4 Target drones
- Enabled Autopilot on F-22 and plane took off
- Enabled Autopilot on Target Drone 1 - Changed team and set guard mode on
- Enabled Guard mode on F-22
- Planes began engaging

Firing AIM-120 (Bay is hard to see in this pic, sorry, but trust me it's from a cargo bay :)
![screenshot74](https://cloud.githubusercontent.com/assets/3577339/17464854/dc425224-5cad-11e6-9c92-53f659d5fe84.png)

Firing JDAM
![screenshot79](https://cloud.githubusercontent.com/assets/3577339/17464850/d56ccc7c-5cad-11e6-8077-d8892a59752e.png)
I wonder if there is something in the enabling of guard mode sequence that is significant.
Have you tried enabling debug labels and seeing if your plane is targeting correctly?

Let me know if you want to swap crafts.

**Comment by Alphasus** [comment] 2016-08-07 21:39
I did enable debug labels, but was effectively unable to make sense of what I saw. What I mostly noticed was that Team A and Team B wouldn't target one another, and the targeting system seemed to be not actually targeting any other craft, regardless of team status. My information may be wrong, but I noticed that both Team A and Team B targets were 0, so it seems like they didn't recognize each other. I'll try to get vesselmover working again, see if that allows for more comprehensive tests too. Target drones would really help.

**Comment by gomker** [comment] 2016-08-07 22:02
I neglected to mention I am using the rotating missile rail as well

**Comment by Alphasus** [comment] 2016-08-07 23:06
I tested again both with and without the rail. Still issues. Competition mode puts them at 8km, well within AMRAAM range but out of gun range. Still won't work.

**Comment by gomker** [comment] 2016-08-07 23:10
I'll try competition mode, I was using vessel switcher to set guard /autopilot on.
Can you try setting manually via Vessel Switcher as I tested to see if that has any affect.

**Comment by Alphasus** [comment] 2016-08-07 23:49
Ok, I'll try once I get the chance using VesselSwitcher.

**Comment by DoctorDavinci** [comment] 2016-08-15 22:04
Tested and found that this issue is a non issue ... I have no problems with missiles being launched from a cargo bay

Although I should note that sometimes a missile doesn't fire from the cargo bay but that is due to the craft not having a radar lock (in the case of AMRAAM's)

No issue found ... recommend closing

**Comment by TheDestroyer111** [comment] 2016-08-16 07:05
Davinci, the issue exists even if you might not have it. The AI does lock, but does not fire.
Do you have the latest version of BDArmory? Tested on the newest one.

**Comment by DoctorDavinci** [comment] 2016-08-16 16:33
Seeing as I am part of the BDAc team, I am quite sure that I have the latest version

**Comment by PapaJoesSoup** [comment] 2016-08-16 17:48
So this begs the question:  what environmental differences exist?  (Mods installed, OS, 64 vs 32 bit etc )

I do not discount that the issue exists, only under what conditions?

**Comment by Nerfclasher** [comment] 2016-08-16 23:18
https://github.com/BahamutoD/BDArmory/issues/36

**Comment by TheDestroyer111** [comment] 2016-08-17 18:08
I think it works no matter the "environmental differences" :P 
Anyway I'm OSX 10.9.4 64bit, with several other mods installed. Issue exists.

**Comment by DoctorDavinci** [comment] 2016-08-20 15:42
Would you kindly list all the mods you are using so we can test the same KSP setup on other systems?

**Comment by TheDestroyer111** [comment] 2016-08-21 08:29
I listed my mods in #28

**Comment by jrodrigv** [comment] 2016-09-03 22:03
Hi all, I have been testing this on competition mode and these are my findings:

- Weird behaviour during the first engage at 8 km: cargo bays opened, target lock acquired, none fired.
- Normal behaviour after the first engage, missiles are fired successfully.

@DoctorDavinci , @PapaJoesSoup  are you experiencing this strange behaviour during the first engage of a Competition mode?

**Comment by DoctorDavinci** [comment] 2016-09-04 00:08
Can't say that I have ... I just looked into this and ran 9 battles using competition mode and each time I have had no issue with the AI firing missiles from within cargo bays

Here's a link to the craft file that I used - https://www.dropbox.com/s/wdkap08wtxcfb0d/DF-54%20Basilides.craft?dl=0

**Comment by TheDestroyer111** [comment] 2016-09-04 07:01
@jrodrigv After some more testing I found out that what you said roughly describes how the issue looks for me. What environment did you get these results in?

**Comment by jrodrigv** [comment] 2016-09-04 15:08
@DoctorDavinci  thanks for you craft and testing.

Guys I think I have narrowed the issue. When a set the missiles to target > 1, it fires even during the first engagement. What is funny is that during the first engagement usually is firing one less that the numbers specified, so if I have set the "Missiles/Target" to 3 is firing 2...

@TheDestroyer111 Can you confirm this doing a competition mode fight with your craft set with "Missiles/Target" to 4?

**Comment by PapaJoesSoup** [comment] 2016-09-04 17:34
That is helpful info.  I will begin looking at this in code as well

**Comment by gomker** [comment] 2016-11-06 20:12
Changing this to enhancement as this looks to be more about tweaking the Guard parameters to be more effective with cargo bays. They will indeed fire, its about the ranges and other settings

**Comment by gomker** [comment] 2017-06-07 06:12
Will update and test again if this is still relevant.

**Closed by gomker** 2017-06-07 06:12 UTC
Labels: AutoPilot, enhancement, Need Confirmation
