### ISSUE TITLE
physics range extender camera bug

### ISSUE THREAD

**Issue by ramwolf44** [PapaJoesSoup/BDArmory#751] opened 2020-01-02 03:02 UTC
Support

##### KSP and BDA Version

1.8
1.8.1

##### OS / ENVIRONMENT

windows 10 x64

##### STEPS TO REPRODUCE
go fast (mach 2+), or switch to a new vessel while the effect is active

##### Log Files
check comment section

**Comment by ramwolf44** [comment] 2020-01-02 03:11
[KSP.log](https://github.com/PapaJoesSoup/BDArmory/files/4014823/KSP.log)

**Comment by jrodrigv** [comment] 2020-01-02 11:02
Sorry but I don't see any explanation of the bug whatsoever.  Please provide a detail explantation of what you are seeing and what is expected.

**Comment by ramwolf44** [comment] 2020-01-05 20:11
sorry i forgot that 

apparently after switching to a new vessel or going above a specific speed (unspecified), the camera will pan out but the view will stay the same. this will result in parts of thew ship suddenly disappearing and a cross section of the inside of the ship being visible.

**Comment by jrodrigv** [comment] 2020-01-05 22:36
That is not a bug, it is a feature :)
You will see a message each 30 seconds informing about it, you can disable the camera clipping on the menu reducing the camera multipler to 0 but you will notice immediately a shaking/shadow glitches. This is because you have landed vessels loaded far from the active flying vessels

**Closed** 2020-01-05 22:36 UTC
