### ISSUE TITLE
Radar not working

### ISSUE THREAD

**Issue by KERBALZ** [PapaJoesSoup/BDArmory#79] opened 2016-11-05 03:02 UTC
I open the radome radar and try to find a target, but nothing appears, not even with boarsight

**Comment by gomker** [comment] 2016-11-05 03:12
When reporting issues please provide the following information:

- version of KSP
- version of BDA
- OS Build and Version
- Link to a full KSP log if reporting a problem
- See this for more information
http://forum.kerbalspaceprogram.com/index.php?/topic/83212-how-to-get-support-read-first/

**Comment by gomker** [comment] 2016-11-05 03:12
This appears to be a duplicate of Issue #73 - There are known issues with Shaders being incorrect for OSX and Linux - this is being addressed. 
The shaders will affect the way Radar works as well.

**Closed by gomker** 2016-11-05 03:12 UTC
Labels: duplicate
